<H1>The First ML Tutorial</H1>

To do analysis, you need some data. Hence download some dataset from the Internet.

1. Download the Automobile dataset from <a href="https://archive.ics.uci.edu/ml/datasets/Automobile">here</a>
2. Download the German Credit dataset from <a href="https://archive.ics.uci.edu/ml/datasets/Statlog+%28German+Credit+Data%29">here</a>
3. Download the Wine Quality dataset (White Wine) from <a href="https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv">here</a>

<H2>Your tasks are as follows</H2>

1. Download the datasets and store them in a file named "Datasets" in your computer
2. Read the datasets using 'pandas'
3. Put all the datasets in a single dictionary named 'all_datasets' in python
4. Produce an output which would show the number of rows and number of columns of each dataset
5. Extract the datatypes of each variable in each dataset. Are they all belonging to correct datatypes?
6. Do you think that some of the variables are containing missing values? Which are those variables? How many missing values are there in each variable in each dataset?
7. Replace the missing values with 'NAN'(actually, numpy.nan)
8. Take out a random sample from the wine quality dataset containing 500 rows and name it as 'wq_rand'. What will you do to get same result in each run?
9. Extract coefficient of variation (CV) for each variable in 'wq_rand' dataset. CV is (standard deviation/mean)
10. Create a new array with 500 random numbers generating from a normal distribution having mean 10 and standard deviation 8. Sort the array and attach the sorted array to the 'wq_rand' dataset
11. Sort the wq_rand dataset with respect to pH variable
12. Create a new dataset from Automobile dataset such that it does not contain any missing value. Name it as auto_cleaned.
13. From auto_cleaned dataset retain only numeric variables and run a PCA retaining 5 components. What proportion of total variance is being explained by those 5 components? How will you extract components such that the explained variance by the components is at least 80%?


In [4]:
import pandas as pd
import numpy as np

In [9]:
# Q2

automobile = pd.read_csv("C:/Users/sivar/Desktop/Praxis/ML(Machine Learining)/Data/auto_data.txt",header=None, na_values="?")
gc = pd.read_table("C:/Users/sivar/Desktop/Praxis/ML(Machine Learining)/Data/german.data.txt", header=None,sep='\s+')
wine = pd.read_csv("C:/Users/sivar/Desktop/Praxis/ML(Machine Learining)/Data/winequality-white.csv",sep=";")

In [10]:
# Q3
all_datasets = {'auto':automobile, 'gc':gc,'wine':wine}

In [11]:
all_datasets.keys()

dict_keys(['auto', 'gc', 'wine'])

In [12]:
gc.head()

0   1    2    3     4    5    6   7    8     9  ...    11  12    13    14  \
0  A11   6  A34  A43  1169  A65  A75   4  A93  A101 ...  A121  67  A143  A152   
1  A12  48  A32  A43  5951  A61  A73   2  A92  A101 ...  A121  22  A143  A152   
2  A14  12  A34  A46  2096  A61  A74   2  A93  A101 ...  A121  49  A143  A152   
3  A11  42  A32  A42  7882  A61  A74   2  A93  A103 ...  A122  45  A143  A153   
4  A11  24  A33  A40  4870  A61  A73   3  A93  A101 ...  A124  53  A143  A153   

  15    16 17    18    19 20  
0  2  A173  1  A192  A201  1  
1  1  A173  1  A191  A201  2  
2  1  A172  2  A191  A201  1  
3  1  A173  2  A191  A201  1  
4  2  A173  2  A191  A201  2  

[5 rows x 21 columns]

In [13]:
# Q4
for key in all_datasets.keys():
    print(all_datasets[key].shape)

(205, 26)
(1000, 21)
(4898, 12)


In [14]:
# Q5
for key in all_datasets.keys():
    print(all_datasets[key].dtypes)

0       int64
1     float64
2      object
3      object
4      object
5      object
6      object
7      object
8      object
9     float64
10    float64
11    float64
12    float64
13      int64
14     object
15     object
16      int64
17     object
18    float64
19    float64
20    float64
21    float64
22    float64
23      int64
24      int64
25    float64
dtype: object
0     object
1      int64
2     object
3     object
4      int64
5     object
6     object
7      int64
8     object
9     object
10     int64
11    object
12     int64
13    object
14    object
15     int64
16    object
17     int64
18    object
19    object
20     int64
dtype: object
fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol        

In [15]:
#Q6 and Q7 are already taken care of while reading the dataset
#Q8
wq_rand = wine.sample(n=500,random_state=12345)

In [17]:
wq_rand.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
4125            6.3              0.17         0.23             5.7      0.048   
4611            5.9              0.42         0.36             2.4      0.034   
2480            6.8              0.32         0.30             1.0      0.049   
485             6.2              0.18         0.38             1.5      0.028   
665             7.8              0.28         0.22             1.4      0.056   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
4125                 44.0                 147.0  0.99382  3.08       0.54   
4611                 19.0                  77.0  0.99184  3.25       0.48   
2480                 22.0                 113.0  0.99289  3.24       0.61   
485                  36.0                 117.0  0.99300  3.47       0.54   
665                  24.0                 130.0  0.99440  3.28       0.48   

      alcohol  quality  
4125     10.0        5  
4611     10.9        5  
2480     10.2        5  
485       9.7        6  
665       9.5        5

In [18]:
# Q9
def cv(inp):
    return(inp.std()/inp.mean())
wq_rand.apply(cv,axis=0)

fixed acidity           0.127535
volatile acidity        0.342357
citric acid             0.331798
residual sugar          0.801710
chlorides               0.473755
free sulfur dioxide     0.473318
total sulfur dioxide    0.305427
density                 0.002848
pH                      0.053152
sulphates               0.221776
alcohol                 0.112964
quality                 0.151659
dtype: float64

In [19]:
# Q9 (alternative solution)
wq_rand.apply(lambda X: X.std()/X.mean(),axis=0)

fixed acidity           0.127535
volatile acidity        0.342357
citric acid             0.331798
residual sugar          0.801710
chlorides               0.473755
free sulfur dioxide     0.473318
total sulfur dioxide    0.305427
density                 0.002848
pH                      0.053152
sulphates               0.221776
alcohol                 0.112964
quality                 0.151659
dtype: float64

In [21]:
# Q10
np.random.seed(seed=1234)
rand_normal = np.random.normal(10,8,500)
rand_normal.sort()
wq_rand['Random_normal'] = rand_normal

In [25]:
# Q11
wq_rand.sort_values(by='pH',ascending=True).head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1758            9.6              0.21         0.28             1.2      0.038   
3589            6.8              0.19         0.71            17.5      0.042   
3563            7.0              0.48         0.12             4.5      0.050   
1372           10.7              0.22         0.56             8.2      0.044   
4659            6.6              0.25         0.25             1.3      0.040   
4693            6.7              0.16         0.32            12.5      0.035   
4288            7.0              0.20         0.33             4.7      0.030   
3952            7.0              0.16         0.30             2.6      0.043   
873            10.3              0.17         0.47             1.4      0.037   
4614            7.1              0.33         0.18             6.3      0.094   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1758                 12.0                  53.0  0.99260  2.80       0.46   
3589                 21.0                 114.0  0.99784  2.85       0.50   
3563                 23.0                  86.0  0.99398  2.86       0.35   
1372                 37.0                 181.0  0.99800  2.87       0.68   
4659                 28.0                  85.0  0.98984  2.87       0.48   
4693                 18.0                 156.0  0.99666  2.88       0.36   
4288                 25.0                  76.0  0.99202  2.88       0.54   
3952                 34.0                  90.0  0.99047  2.88       0.47   
873                   5.0                  33.0  0.99390  2.89       0.28   
4614                 27.0                 166.0  0.99474  2.90       0.49   

      alcohol  quality  Random_normal  
1758     10.6        5      15.552826  
3589      9.5        6      16.372759  
3563      9.0        5      21.109179  
1372      9.5        6      14.216372  
4659     11.2        6      12.463751  
4693      9.0        6      20.568845  
4288     10.5        6      10.294290  
3952     11.2        6      10.188461  
873       9.6        3       1.359228  
4614      9.5        5      26.782406

In [26]:
# Q12
auto_cleaned = automobile.dropna()

In [27]:
# Q13
num_vars = [var for var in auto_cleaned.columns if auto_cleaned.iloc[:,var].dtypes != 'object']
from sklearn.decomposition import PCA

my_pca1 = PCA(n_components = 5)
PC1 = my_pca1.fit_transform(auto_cleaned[num_vars])
my_pca2 = PCA(n_components=0.9,svd_solver='full')
PC2 = my_pca2.fit_transform(auto_cleaned[num_vars])

In [28]:
PC1

array([[  2.48293220e+03,   4.60135973e+02,  -2.45605552e+02,
          2.68591490e+01,   6.84262304e+00],
       [  6.00896419e+03,   4.75558893e+02,  -1.16737734e+01,
          2.30669156e+01,   1.40088931e+01],
       [  6.26970043e+03,   4.78690998e+02,  -1.01871340e+01,
          1.51337858e+01,   1.96301824e+01],
       [  1.24352781e+04,   5.92178324e+02,  -2.06775091e+02,
          3.21806181e+00,   1.79554664e+01],
       [  4.95615676e+03,   8.08574370e+02,  -3.22131860e+02,
          4.12059660e+01,   2.22290007e+01],
       [  5.44977313e+03,   8.20354967e+02,  -3.57161951e+02,
          3.99385335e+01,   2.27486376e+01],
       [  9.52809887e+03,  -6.61491769e+02,  -5.47378795e+02,
          6.97903565e+01,  -1.63123112e+01],
       [  9.66674616e+03,  -6.65935573e+02,  -5.02746219e+02,
          6.94228832e+01,  -1.28420079e+01],
       [ -6.34868289e+03,  -2.79909589e+01,  -5.21008260e+02,
          3.57827563e+00,   5.73343638e+00],
       [ -5.18352377e+03,   2.4182784

In [85]:
from scipy.linalg import eig

In [93]:
cov_mat = auto_cleaned[num_vars].cov()

In [94]:
eig(cov_mat)

(array([3.47428193e+07+0.j, 2.13969294e+05+0.j, 4.33559739e+04+0.j,
        1.14671321e+03+0.j, 3.24060200e+02+0.j, 1.10975121e+02+0.j,
        3.44256849e+01+0.j, 1.99249694e+01+0.j, 5.40473691e+00+0.j,
        4.67779398e+00+0.j, 2.13727342e+00+0.j, 9.12913190e-01+0.j,
        7.16623230e-01+0.j, 4.37577384e-01+0.j, 2.75495764e-02+0.j,
        6.70499938e-02+0.j]),
 array([[ 3.31167037e-05, -4.81466000e-04,  1.08038258e-03,
         -1.90654746e-02,  8.76148869e-03,  1.10239689e-03,
          3.85230583e-02,  6.63090469e-04,  3.17400458e-02,
         -2.13139077e-01, -4.52962266e-02, -3.24141009e-01,
          6.11832126e-01, -6.85631090e-01, -9.44191998e-03,
          3.63160043e-04],
        [-1.22265463e-03, -2.17113034e-02,  7.07231181e-03,
         -9.81690974e-01, -1.82553872e-01, -3.29324001e-02,
         -2.27730509e-02,  7.13097161e-03, -3.37915768e-03,
          1.60164140e-02, -1.63163198e-02,  1.08266743e-02,
         -4.74053979e-03,  1.02710737e-02, -8.14991297e-04,
   