In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [5]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv(url, names = names)
array = data.values # converting dataset into array

In [24]:
x = array[:,0:8] #separating independant and dependant variable
y = array[:,8]

In [27]:
sc = MinMaxScaler() # Scaling the data on basis of Normalisation
sc_x = sc.fit_transform(x)

In [34]:
np.set_printoptions(precision=2)# keeping decimal values till 2 places
print(sc_x[0:5])

[[ 0.35  0.74  0.59  0.35  0.    0.5   0.23  0.48]
 [ 0.06  0.43  0.54  0.29  0.    0.4   0.12  0.17]
 [ 0.47  0.92  0.52  0.    0.    0.35  0.25  0.18]
 [ 0.06  0.45  0.54  0.23  0.11  0.42  0.04  0.  ]
 [ 0.    0.69  0.33  0.35  0.2   0.64  0.94  0.2 ]]


In [38]:
from sklearn.preprocessing import StandardScaler # Standardization i.e Z score with mean = 0 and sd =1
ss = StandardScaler()
ss_x = ss.fit_transform(x)
ss_x[0:5]


array([[ 0.64,  0.85,  0.15,  0.91, -0.69,  0.2 ,  0.47,  1.43],
       [-0.84, -1.12, -0.16,  0.53, -0.69, -0.68, -0.37, -0.19],
       [ 1.23,  1.94, -0.26, -1.29, -0.69, -1.1 ,  0.6 , -0.11],
       [-0.84, -1.  , -0.16,  0.15,  0.12, -0.49, -0.92, -1.04],
       [-1.14,  0.5 , -1.5 ,  0.91,  0.77,  1.41,  5.48, -0.02]])

In [47]:
# can be used in KNN algorithm
from sklearn.preprocessing import Normalizer #This preprocessing can be useful for sparse datasets (lots of zeros)
n = Normalizer()
n_x = n.fit_transform(x)
n_x[0:5]

array([[ 0.03,  0.83,  0.4 ,  0.2 ,  0.  ,  0.19,  0.  ,  0.28],
       [ 0.01,  0.72,  0.56,  0.24,  0.  ,  0.22,  0.  ,  0.26],
       [ 0.04,  0.92,  0.32,  0.  ,  0.  ,  0.12,  0.  ,  0.16],
       [ 0.01,  0.59,  0.44,  0.15,  0.62,  0.19,  0.  ,  0.14],
       [ 0.  ,  0.6 ,  0.17,  0.15,  0.73,  0.19,  0.01,  0.14]])

In [43]:
#All values above the threshold are marked 1 and all equal to or below are marked as 0.

from sklearn.preprocessing import Binarizer
b = Binarizer(threshold = 0.5)
b_x = b.fit_transform(x)
b_x

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  0.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       ..., 
       [ 1.,  1.,  1., ...,  1.,  0.,  1.],
       [ 1.,  1.,  1., ...,  1.,  0.,  1.],
       [ 1.,  1.,  1., ...,  1.,  0.,  1.]])